# Generated by Django 4.1.7 on 2023-02-21 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='add_featre_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='add_garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255)),
                ('mobile', models.IntegerField()),
                ('g_image', models.ImageField(upload_to='')),
                ('g_discription', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='add_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_price', models.IntegerField()),
                ('discription', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='l_bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_brand', models.CharField(max_length=255)),
                ('b_model', models.CharField(max_length=255)),
                ('b_year', models.IntegerField()),
                ('b_km_driven', models.IntegerField()),
                ('b_Color', models.CharField(max_length=255)),
                ('b_no_owner', models.IntegerField()),
                ('b_engine_CC', models.CharField(max_length=255)),
                ('b_insurence_validity', models.IntegerField()),
                ('b_transmisson', models.CharField(choices=[('automatic', 'AUTOMATIC'), ('manual', 'MANUAL')], default='manual', max_length=255)),
                ('b_fuel', models.CharField(choices=[('petrol', 'PETROL'), ('deisel', 'DEISEL'), ('hybrid', 'HYBRID'), ('ev', 'ELECTRIC')], default='petrol', max_length=255)),
                ('b_discription', models.CharField(max_length=255)),
                ('b_image', models.ImageField(upload_to='')),
                ('b_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='l_cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_brand', models.CharField(max_length=255)),
                ('l_model', models.CharField(max_length=255)),
                ('l_year', models.IntegerField()),
                ('l_km_driven', models.IntegerField()),
                ('l_Color', models.CharField(max_length=255)),
                ('l_no_owner', models.IntegerField()),
                ('l_engine_CC', models.CharField(max_length=255)),
                ('l_insurence_validity', models.IntegerField()),
                ('l_transmisson', models.CharField(choices=[('automatic', 'AUTOMATIC'), ('manual', 'MANUAL')], default='manual', max_length=255)),
                ('l_fuel', models.CharField(choices=[('petrol', 'PETROL'), ('deisel', 'DEISEL'), ('hybrid', 'HYBRID'), ('ev', 'ELECTRIC')], default='petrol', max_length=255)),
                ('l_discription', models.CharField(max_length=255)),
                ('l_image', models.ImageField(upload_to='')),
                ('l_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test_drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('select_date', models.DateField()),
                ('select_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('car_model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=100)),
                ('type_of_service', models.CharField(choices=[('Running Repair', 'Running Repair'), ('Water service', 'Water service'), ('Accessories fitting', 'Accessories fitting'), ('Paint & polish', 'Paint & polish'), ('Oil change', 'Oil change'), ('Other', 'Other')], max_length=150)),
                ('mode_of_vehicle_taking', models.CharField(choices=[('Pickup & Drop', 'Pickup & Drop'), ('Pickup only', 'Pickup only'), ('Drop only', 'Drop only'), ('Not required', 'Not required')], max_length=100)),
                ('service_booked_on', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SELL_CAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('km_driven', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('No_of_owners', models.IntegerField()),
                ('engine_cc', models.CharField(max_length=50)),
                ('Insurance_validity', models.CharField(max_length=50)),
                ('year_of_registration', models.IntegerField()),
                ('mode_of_transmission', models.CharField(choices=[('Manual', 'Manual Transmission'), ('Automatic', 'Automatic Transmission')], max_length=100)),
                ('type_of_vehicle', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=100)),
                ('vehicle_description', models.TextField(help_text='You can write more about your vehicle here')),
                ('vehicle_images', models.ImageField(upload_to='images/')),
                ('extras', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safariapp.add_product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Jammu Kashmir', 'Jammu Kashmir'), ('Nagaland', 'Nagaland'), ('Rajasthan', 'Rajasthan'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Ladakh', 'Ladakh'), ('Jharkhand', 'Jharkhand'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Bihar', 'Bihar'), ('Tripura', 'Tripura'), ('Telangana', 'Telangana'), ('Chhattisgarh', 'Chhattisgarh'), ('Punjab', 'Punjab'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Maharashtra', 'Maharashtra'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Meghalaya', 'Meghalaya'), ('Manipur', 'Manipur'), ('Tamil Nadu', 'Tamil Nadu'), ('Kerala', 'Kerala'), ('Haryana', 'Haryana'), ('Gujarat', 'Gujarat'), ('Karnataka', 'Karnataka'), ('Assam', 'Assam')], max_length=100)),
                ('pincode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='add_vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('km_driven', models.IntegerField()),
                ('mailage', models.IntegerField()),
                ('Color', models.CharField(max_length=255)),
                ('no_owner', models.IntegerField()),
                ('engine_CC', models.CharField(max_length=255)),
                ('insurence_validity', models.IntegerField()),
                ('year_of_registration', models.IntegerField()),
                ('transmisson', models.CharField(choices=[('automatic', 'AUTOMATIC'), ('manual', 'MANUAL')], default='manual', max_length=255)),
                ('fuel', models.CharField(choices=[('petrol', 'PETROL'), ('deisel', 'DEISEL'), ('hybrid', 'HYBRID'), ('ev', 'ELECTRIC')], default='petrol', max_length=255)),
                ('discription', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('parking_sensor', models.BooleanField(default=False, verbose_name='parking_sensor')),
                ('center_lock', models.BooleanField(default=False, verbose_name='center_lock')),
                ('Rear_camera', models.BooleanField(default=False, verbose_name='Rear_camera')),
                ('Navigation_system', models.BooleanField(default=False, verbose_name='Navigation_system')),
                ('Adjustable_stearing', models.BooleanField(default=False, verbose_name='Adjustable_stearing')),
                ('c_price', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
