# Generated by Django 4.1.5 on 2023-02-06 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('confirm', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='sell_your_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('Km_driven', models.CharField(max_length=255)),
                ('mailage', models.CharField(max_length=255)),
                ('Color', models.CharField(max_length=255)),
                ('no_owner', models.CharField(max_length=255)),
                ('engine_CC', models.CharField(max_length=255)),
                ('insurence_validity', models.CharField(max_length=255)),
                ('year_of_registraion', models.CharField(max_length=255)),
                ('transmisson', models.CharField(choices=[('automatic', 'AUTOMATIC'), ('manual', 'MANUAL')], default='manual', max_length=255)),
                ('fuel', models.CharField(choices=[('petrol', 'PETROL'), ('deisel', 'DEISEL'), ('hybrid', 'HYBRID'), ('ev', 'ELECTRIC')], default='petrol', max_length=255)),
                ('discription', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=None)),
                ('parking_sensor', models.BooleanField(default=False, verbose_name='parking_sensor')),
                ('center_lock', models.BooleanField(default=False, verbose_name='center_lock')),
                ('Rear_camera', models.BooleanField(default=False, verbose_name='Rear_camera')),
                ('Navigation_system', models.BooleanField(default=False, verbose_name='Navigation_system')),
                ('Adjustable_stearing', models.BooleanField(default=False, verbose_name='Adjustable_stearing')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.member', to_field='user_name')),
            ],
        ),
    ]
