# Generated by Django 4.1.5 on 2023-02-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_sell_your_car_user_name_sell_your_car_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell_your_car',
            old_name='Km_driven',
            new_name='km_driven',
        ),
    ]
