# Generated by Django 4.1.5 on 2023-02-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_km_driven_sell_your_car_km_driven'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sell_your_car',
            old_name='year_of_registraion',
            new_name='year_of_registration',
        ),
    ]
