# Generated by Django 4.1.5 on 2023-02-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('kerala', 'KERALA'), ('tamilnadu', 'TAMILNADU'), ('karnataka', 'KARNATAKA')], default='kerala', max_length=255),
        ),
    ]
