# Generated by Django 4.1.5 on 2023-02-10 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=255)),
                ('car', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('reg_no', models.IntegerField()),
                ('serv', models.CharField(choices=[('water', 'WATER'), ('running', 'RUNNING')], default='water', max_length=255)),
                ('deliv', models.CharField(choices=[('pickup', 'PICKUP'), ('drop', 'DROP'), ('pick and drop', 'PICKUP AND DROP'), ('not required', 'NOT REQUIRED')], default='not reqired', max_length=255)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
