# Generated by Django 4.1.5 on 2023-02-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_service_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='deliv',
            field=models.CharField(max_length=255),
        ),
    ]
