# Generated by Django 4.1.5 on 2023-02-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_service_deliv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_your_car',
            name='insurence_validity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sell_your_car',
            name='km_driven',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sell_your_car',
            name='mailage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sell_your_car',
            name='no_owner',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sell_your_car',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sell_your_car',
            name='year_of_registration',
            field=models.IntegerField(),
        ),
    ]
