# Generated by Django 4.1.5 on 2023-02-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_sell_your_car_insurence_validity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell_your_car',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='deliv',
            field=models.CharField(choices=[('pickup', 'PICKUP'), ('drop', 'DROP'), ('pick and drop', 'PICKUP AND DROP'), ('not required', 'NOT REQUIRED')], default='PICKUP', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='serv',
            field=models.CharField(choices=[('water service', 'WATER SERVICE'), ('running repair', 'RUNNING REPAIR'), ('Accessories fitiing', 'ACCESSORIES FITTING'), ('Paint & polish', 'PAINT & POLISH'), ('Oil change', 'OIL CHANGE'), ('others', 'OTHERS')], default='water', max_length=255),
        ),
    ]
