# Generated by Django 4.1.5 on 2023-02-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_sell_your_car_image_alter_service_deliv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('km_driven', models.IntegerField()),
                ('mailage', models.IntegerField()),
                ('Color', models.CharField(max_length=255)),
                ('no_owner', models.IntegerField()),
                ('engine_CC', models.CharField(max_length=255)),
                ('insurence_validity', models.IntegerField()),
                ('year_of_registration', models.IntegerField()),
                ('transmisson', models.CharField(choices=[('automatic', 'AUTOMATIC'), ('manual', 'MANUAL')], default='manual', max_length=255)),
                ('fuel', models.CharField(choices=[('petrol', 'PETROL'), ('deisel', 'DEISEL'), ('hybrid', 'HYBRID'), ('ev', 'ELECTRIC')], default='petrol', max_length=255)),
                ('discription', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('parking_sensor', models.BooleanField(default=False, verbose_name='parking_sensor')),
                ('center_lock', models.BooleanField(default=False, verbose_name='center_lock')),
                ('Rear_camera', models.BooleanField(default=False, verbose_name='Rear_camera')),
                ('Navigation_system', models.BooleanField(default=False, verbose_name='Navigation_system')),
                ('Adjustable_stearing', models.BooleanField(default=False, verbose_name='Adjustable_stearing')),
            ],
        ),
    ]
