# Generated by Django 4.1.5 on 2023-02-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_add_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_vehicle',
            name='c_price',
            field=models.IntegerField(null=True),
        ),
    ]
