# Generated by Django 4.1.5 on 2023-02-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_add_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='l_bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_brand', models.CharField(max_length=255)),
                ('b_model', models.CharField(max_length=255)),
                ('b_year', models.IntegerField()),
                ('b_km_driven', models.IntegerField()),
                ('b_Color', models.CharField(max_length=255)),
                ('b_no_owner', models.IntegerField()),
                ('b_engine_CC', models.CharField(max_length=255)),
                ('b_insurence_validity', models.IntegerField()),
                ('b_transmisson', models.CharField(choices=[('automatic', 'AUTOMATIC'), ('manual', 'MANUAL')], default='manual', max_length=255)),
                ('b_fuel', models.CharField(choices=[('petrol', 'PETROL'), ('deisel', 'DEISEL'), ('hybrid', 'HYBRID'), ('ev', 'ELECTRIC')], default='petrol', max_length=255)),
                ('b_discription', models.CharField(max_length=255)),
                ('b_image', models.ImageField(upload_to='')),
                ('b_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='l_cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_brand', models.CharField(max_length=255)),
                ('l_model', models.CharField(max_length=255)),
                ('l_year', models.IntegerField()),
                ('l_km_driven', models.IntegerField()),
                ('l_Color', models.CharField(max_length=255)),
                ('l_no_owner', models.IntegerField()),
                ('l_engine_CC', models.CharField(max_length=255)),
                ('l_insurence_validity', models.IntegerField()),
                ('l_transmisson', models.CharField(choices=[('automatic', 'AUTOMATIC'), ('manual', 'MANUAL')], default='manual', max_length=255)),
                ('l_fuel', models.CharField(choices=[('petrol', 'PETROL'), ('deisel', 'DEISEL'), ('hybrid', 'HYBRID'), ('ev', 'ELECTRIC')], default='petrol', max_length=255)),
                ('l_discription', models.CharField(max_length=255)),
                ('l_image', models.ImageField(upload_to='')),
                ('l_price', models.IntegerField()),
            ],
        ),
    ]
