# Generated by Django 4.1.5 on 2023-02-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_l_bikes_l_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_featre_ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='add_garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255)),
                ('mobile', models.IntegerField()),
                ('g_image', models.ImageField(upload_to='')),
                ('g_discription', models.CharField(max_length=255)),
            ],
        ),
    ]
