# Generated by Django 4.1.5 on 2023-02-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_add_featre_ad_add_garage'),
    ]

    operations = [
        migrations.CreateModel(
            name='dis_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=255)),
                ('p_price', models.IntegerField()),
                ('discription', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
