# Generated by Django 4.1.5 on 2023-02-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_dis_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_vehicle',
            name='image1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='add_vehicle',
            name='image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='add_vehicle',
            name='image3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='add_vehicle',
            name='image4',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
