# Generated by Django 4.1.5 on 2023-02-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_add_vehicle_image1_add_vehicle_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='l_bikes',
            name='b_image1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='l_bikes',
            name='b_image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='l_bikes',
            name='b_image3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='l_bikes',
            name='b_image4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='l_cars',
            name='l_image1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='l_cars',
            name='l_image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='l_cars',
            name='l_image3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='l_cars',
            name='l_image4',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
