"""
Django settings for safari_cars project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
# import django
# django.setup()
# import os
# import django
# os.environ.setdefault("DJANGO_SETTINGS_MODULE", "safari_cars.settings")
# django.setup()

# Django dependencies below this line
# from safariapp.models import MyModel
from pathlib import Path
# from django.urls import reverse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-72uo3ut#@6eqfurcve8i!o&=67ongiii_dbr*_l)ku#0f3w1o9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'safariapp',
    'crispy_forms',
    'django_social_share',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
   
    # 'social.apps.django_app.default',
    # 'social.apps.django_app.default',
    "django.contrib.sites",  # new
    # 3rd party
    "allauth", # new
    "allauth.account", # new
    "allauth.socialaccount", # new
    # social providers
    "allauth.socialaccount.providers.github", # new
    "allauth.socialaccount.providers.facebook",
    "allauth.socialaccount.providers.google",

    "allauth.socialaccount.providers.twitter", # new

    'captcha',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATE_CONTEXT_PROCESSORS = (
   'django.contrib.auth.context_processors.auth',
   'django.core.context_processors.debug',
   'django.core.context_processors.i18n',
   'django.core.context_processors.media',
   'django.core.context_processors.static',
   'django.core.context_processors.tz',
   'django.contrib.messages.context_processors.messages',
#    'social.apps.django_app.context_processors.backends',
#    'social.apps.django_app.context_processors.login_redirect',
)


# AUTHENTICATION_BACKENDS = (
#    'social.backends.facebook.FacebookOAuth2',
#    'social.backends.google.GoogleOAuth2',
#    'social.backends.twitter.TwitterOAuth',
#    'django.contrib.auth.backends.ModelBackend',
# )

ROOT_URLCONF = 'safari_cars.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
                    # 'social.backends.facebook.FacebookOAuth2',
                    # 'social.backends.google.GoogleOAuth2',
                    # 'social.backends.twitter.TwitterOAuth',
    
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'allauth.account.context_processors.account',
                # 'allauth.socialaccount.context_processors.socialaccount',
                # 'social.apps.django_app.context_processors.backends',
                # 'social.apps.django_app.context_processors.login_redirect',

            ],
        },
    },
]

WSGI_APPLICATION = 'safari_cars.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
import os
STATIC_URL = 'static/'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static')
]

MEDIA_URL = '/media/'
MEDIA_ROOT=  os.path.join(BASE_DIR,'media')


# SOCIAL_AUTH_FACEBOOK_KEY = '16...535'
# SOCIAL_AUTH_FACEBOOK_SECRET = '857..4bb9d'


# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '8507...kg6.apps.googleusercontent.com'
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'gUzw...CD32-'

# SOCIAL_AUTH_TWITTER_KEY = 'lNx...yQH8u'
# SOCIAL_AUTH_TWITTER_SECRET = '8virx...Div4dwB'
   


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_TEMPLATE_PACK = 'bootstrap4'
# EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST='smtp.gmail.com'
# EMAIL_PORT=587
# EMAIL_USE_TLS=True
# EMAIL_HOST_USER="Your email"
# EMAIL_HOST_PASSWORD="Your password"
# SOCIALACCOUNT_PROVIDERS = {
#     'github': {
#         # From https://developer.twitter.com
#         'APP': {
#             'client_id': os.environ['GITHUB_API_KEY'],
#             'secret': os.environ['GITHUB_API_SECRET'],
#             'key': os.environ['GITHUB_APP_ID'],
#         }
#     },
# }






AUTHENTICATION_BACKENDS = (
    "allauth.account.auth_backends.AuthenticationBackend",
    "django.contrib.auth.backends.ModelBackend",
)

SITE_ID = 4
ACCOUNT_EMAIL_VERIFICATION = "none"
LOGIN_REDIRECT_URL='/'
ACCOUNT_LOGOUT_ON_GET = True

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# EMAIL_HOST = 'smtp.sendgrid.net'
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'testsite_app'
# EMAIL_HOST_PASSWORD = 'mys3cr3tp4ssw0rd'
# EMAIL_USE_TLS = True
# DEFAULT_FROM_EMAIL = 'TestSite Team <noreply@example.com>'
EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend"
# EMAIL_BACKEND="django.core.mail.backends.console.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'pythonperinthalmanna1@gmail.com ' #your email-id
EMAIL_HOST_PASSWORD = 'xjdgmehsdsvgykop' #your password
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
PASSWORD_RESET_TIMEOUT = 14400

RECAPTCHA_PUBLIC_KEY = '6LddA3kgAAAAAPf1mAJmEc7Ku0cssbD5QMha09NT'
RECAPTCHA_PRIVATE_KEY = '6LddA3kgAAAAAJY-2-Q0J3QX83DFJwFR1hXqmN8q'
SILENCED_SYSTEM_CHECKS = ['captcha.recaptcha_test_key_error']

RAZOR_KEY_ID='rzp_test_4RXNPsNgwiC9L2'
RAZOR_KEY_SECRET='zhu7kV6aHzK3mwCugV9ASAfG'

# ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'